//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Scriban.Helpers;
using Scriban.Parsing;
using Scriban.Runtime;
using Scriban.Syntax;
using System.Numerics;

namespace Scriban.Syntax
{
#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptAnonymousFunction
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 1;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => Function;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptArgumentBinary
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 1;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => OperatorToken;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptArrayInitializerExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => OpenBracketToken,
                1 => Values,
                2 => CloseBracketToken,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptAssignExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => Target,
                1 => EqualToken,
                2 => Value,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptBinaryExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => Left,
                1 => OperatorToken,
                2 => Right,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptBlockStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 1;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => Statements;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptBreakStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 1;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => BreakKeyword;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptCaptureStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => CaptureKeyword,
                1 => Target,
                2 => Body,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptCaseStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => CaseKeyword,
                1 => Value,
                2 => Body,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptConditionalExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 5;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => Condition,
                1 => QuestionToken,
                2 => ThenValue,
                3 => ColonToken,
                4 => ElseValue,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptContinueStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 1;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => ContinueKeyword;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptElseStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 2;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => ElseKeyword,
                1 => Body,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptEndStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 1;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => EndKeyword;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptEscapeStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 0;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => null;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptExpressionStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 1;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => Expression;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptForStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 7;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => ForOrTableRowKeyword,
                1 => Variable,
                2 => InKeyword,
                3 => Iterator,
                4 => NamedArguments,
                5 => Body,
                6 => Else,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptFrontMatter
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => StartMarker,
                1 => Statements,
                2 => EndMarker,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptFunction
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 7;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => FuncToken,
                1 => NameOrDoToken,
                2 => OpenParen,
                3 => Parameters,
                4 => CloseParen,
                5 => EqualToken,
                6 => Body,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptFunctionCall
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 4;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => Target,
                1 => OpenParent,
                2 => Arguments,
                3 => CloseParen,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptIdentifier
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 0;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => null;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptIfStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 5;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => ElseKeyword,
                1 => IfKeyword,
                2 => Condition,
                3 => Then,
                4 => Else,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptImportStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 2;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => ImportKeyword,
                1 => Expression,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptIncrementDecrementExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 2;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => OperatorToken,
                1 => Right,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptIndexerExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 4;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => Target,
                1 => OpenBracket,
                2 => Index,
                3 => CloseBracket,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptInterpolatedExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => OpenBrace,
                1 => Expression,
                2 => CloseBrace,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptInterpolatedStringExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 1;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => Parts;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptIsEmptyExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 4;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => Target,
                1 => DotToken,
                2 => Member,
                3 => QuestionToken,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptKeyword
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 0;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => null;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptLiteral
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 0;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => null;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptMemberExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => Target,
                1 => DotToken,
                2 => Member,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptNamedArgument
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => Name,
                1 => ColonToken,
                2 => Value,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptNestedExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => OpenParen,
                1 => Expression,
                2 => CloseParen,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptNopStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 0;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => null;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptObjectInitializerExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => OpenBrace,
                1 => Members,
                2 => CloseBrace,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptObjectMember
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => Name,
                1 => ColonToken,
                2 => Value,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptPage
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 2;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => FrontMatter,
                1 => Body,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptParameter
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => Name,
                1 => EqualOrTripleDotToken,
                2 => DefaultValue,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptPipeCall
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => From,
                1 => PipeToken,
                2 => To,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptRawStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 0;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => null;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptReadOnlyStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 2;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => ReadOnlyKeyword,
                1 => Variable,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptReturnStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 2;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => RetKeyword,
                1 => Expression,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptTableRowStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 7;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => ForOrTableRowKeyword,
                1 => Variable,
                2 => InKeyword,
                3 => Iterator,
                4 => NamedArguments,
                5 => Body,
                6 => Else,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptThisExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 1;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => ThisKeyword;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptToken
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 0;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => null;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptUnaryExpression
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 2;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => OperatorToken,
                1 => Right,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptVariableGlobal
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 0;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => null;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptVariableLocal
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 0;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index) => null;
        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptWhenStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 4;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => WhenKeyword,
                1 => Values,
                2 => Body,
                3 => Next,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptWhileStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => WhileKeyword,
                1 => Condition,
                2 => Body,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptWithStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => WithKeyword,
                1 => Name,
                2 => Body,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    partial class ScriptWrapStatement
    {
        /// <inheritdoc/>
        public override int ChildrenCount => 3;

        /// <inheritdoc/>
        protected override ScriptNode GetChildrenImpl(int index)
        {
            return index switch
            {
                0 => WrapKeyword,
                1 => Target,
                2 => Body,
                _ => null
            };
        }

        /// <inheritdoc/>
        public override void Accept(ScriptVisitor visitor) => visitor.Visit(this);
        /// <inheritdoc/>
        public override TResult Accept<TResult>(ScriptVisitor<TResult> visitor) => visitor.Visit(this);
    }


#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    abstract partial class ScriptRewriter
    {
        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptAnonymousFunction node)
        {
            var newFunction = (ScriptFunction)Visit((ScriptNode)node.Function);
            return new ScriptAnonymousFunction() { Function = newFunction };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptArgumentBinary node)
        {
            var newOperatorToken = (ScriptToken)Visit((ScriptNode)node.OperatorToken);
            return new ScriptArgumentBinary() { OperatorToken = newOperatorToken, Operator = node.Operator };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptArrayInitializerExpression node)
        {
            var newOpenBracketToken = (ScriptToken)Visit((ScriptNode)node.OpenBracketToken);
            var newValues = VisitAll(node.Values);
            var newCloseBracketToken = (ScriptToken)Visit((ScriptNode)node.CloseBracketToken);
            return new ScriptArrayInitializerExpression() { OpenBracketToken = newOpenBracketToken, Values = newValues, CloseBracketToken = newCloseBracketToken };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptAssignExpression node)
        {
            var newTarget = (ScriptExpression)Visit((ScriptNode)node.Target);
            var newEqualToken = (ScriptToken)Visit((ScriptNode)node.EqualToken);
            var newValue = (ScriptExpression)Visit((ScriptNode)node.Value);
            return new ScriptAssignExpression() { Target = newTarget, EqualToken = newEqualToken, Value = newValue };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptBinaryExpression node)
        {
            var newLeft = (ScriptExpression)Visit((ScriptNode)node.Left);
            var newOperatorToken = (ScriptToken)Visit((ScriptNode)node.OperatorToken);
            var newRight = (ScriptExpression)Visit((ScriptNode)node.Right);
            return new ScriptBinaryExpression() { Left = newLeft, OperatorToken = newOperatorToken, Right = newRight, Operator = node.Operator };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptBlockStatement node)
        {
            var newStatements = VisitAll(node.Statements);
            return new ScriptBlockStatement() { Statements = newStatements };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptBreakStatement node)
        {
            var newBreakKeyword = (ScriptKeyword)Visit((ScriptNode)node.BreakKeyword);
            return new ScriptBreakStatement() { BreakKeyword = newBreakKeyword };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptCaptureStatement node)
        {
            var newCaptureKeyword = (ScriptKeyword)Visit((ScriptNode)node.CaptureKeyword);
            var newTarget = (ScriptExpression)Visit((ScriptNode)node.Target);
            var newBody = (ScriptBlockStatement)Visit((ScriptNode)node.Body);
            return new ScriptCaptureStatement() { CaptureKeyword = newCaptureKeyword, Target = newTarget, Body = newBody };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptCaseStatement node)
        {
            var newCaseKeyword = (ScriptKeyword)Visit((ScriptNode)node.CaseKeyword);
            var newValue = (ScriptExpression)Visit((ScriptNode)node.Value);
            var newBody = (ScriptBlockStatement)Visit((ScriptNode)node.Body);
            return new ScriptCaseStatement() { CaseKeyword = newCaseKeyword, Value = newValue, Body = newBody };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptConditionalExpression node)
        {
            var newCondition = (ScriptExpression)Visit((ScriptNode)node.Condition);
            var newQuestionToken = (ScriptToken)Visit((ScriptNode)node.QuestionToken);
            var newThenValue = (ScriptExpression)Visit((ScriptNode)node.ThenValue);
            var newColonToken = (ScriptToken)Visit((ScriptNode)node.ColonToken);
            var newElseValue = (ScriptExpression)Visit((ScriptNode)node.ElseValue);
            return new ScriptConditionalExpression() { Condition = newCondition, QuestionToken = newQuestionToken, ThenValue = newThenValue, ColonToken = newColonToken, ElseValue = newElseValue };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptContinueStatement node)
        {
            var newContinueKeyword = (ScriptKeyword)Visit((ScriptNode)node.ContinueKeyword);
            return new ScriptContinueStatement() { ContinueKeyword = newContinueKeyword };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptElseStatement node)
        {
            var newElseKeyword = (ScriptKeyword)Visit((ScriptNode)node.ElseKeyword);
            var newBody = (ScriptBlockStatement)Visit((ScriptNode)node.Body);
            return new ScriptElseStatement() { ElseKeyword = newElseKeyword, Body = newBody };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptEndStatement node)
        {
            var newEndKeyword = (ScriptKeyword)Visit((ScriptNode)node.EndKeyword);
            return new ScriptEndStatement() { EndKeyword = newEndKeyword, ExpectEos = node.ExpectEos };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptEscapeStatement node)
        {
            return new ScriptEscapeStatement() { WhitespaceMode = node.WhitespaceMode, Indent = node.Indent, IsEntering = node.IsEntering, EscapeCount = node.EscapeCount };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptExpressionStatement node)
        {
            var newExpression = (ScriptExpression)Visit((ScriptNode)node.Expression);
            return new ScriptExpressionStatement() { Expression = newExpression };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptForStatement node)
        {
            var newForOrTableRowKeyword = (ScriptKeyword)Visit((ScriptNode)node.ForOrTableRowKeyword);
            var newVariable = (ScriptExpression)Visit((ScriptNode)node.Variable);
            var newInKeyword = (ScriptKeyword)Visit((ScriptNode)node.InKeyword);
            var newIterator = (ScriptExpression)Visit((ScriptNode)node.Iterator);
            var newNamedArguments = VisitAll(node.NamedArguments);
            var newBody = (ScriptBlockStatement)Visit((ScriptNode)node.Body);
            var newElse = (ScriptElseStatement)Visit((ScriptNode)node.Else);
            return new ScriptForStatement() { ForOrTableRowKeyword = newForOrTableRowKeyword, Variable = newVariable, InKeyword = newInKeyword, Iterator = newIterator, NamedArguments = newNamedArguments, Body = newBody, Else = newElse, SetContinue = node.SetContinue };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptFrontMatter node)
        {
            var newStartMarker = (ScriptToken)Visit((ScriptNode)node.StartMarker);
            var newStatements = (ScriptBlockStatement)Visit((ScriptNode)node.Statements);
            var newEndMarker = (ScriptToken)Visit((ScriptNode)node.EndMarker);
            return new ScriptFrontMatter() { StartMarker = newStartMarker, Statements = newStatements, EndMarker = newEndMarker };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptFunction node)
        {
            var newFuncToken = (ScriptKeyword)Visit((ScriptNode)node.FuncToken);
            var newNameOrDoToken = (ScriptNode)Visit((ScriptNode)node.NameOrDoToken);
            var newOpenParen = (ScriptToken)Visit((ScriptNode)node.OpenParen);
            var newParameters = VisitAll(node.Parameters);
            var newCloseParen = (ScriptToken)Visit((ScriptNode)node.CloseParen);
            var newEqualToken = (ScriptToken)Visit((ScriptNode)node.EqualToken);
            var newBody = (ScriptStatement)Visit((ScriptNode)node.Body);
            return new ScriptFunction() { FuncToken = newFuncToken, NameOrDoToken = newNameOrDoToken, OpenParen = newOpenParen, Parameters = newParameters, CloseParen = newCloseParen, EqualToken = newEqualToken, Body = newBody };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptFunctionCall node)
        {
            var newTarget = (ScriptExpression)Visit((ScriptNode)node.Target);
            var newOpenParent = (ScriptToken)Visit((ScriptNode)node.OpenParent);
            var newArguments = VisitAll(node.Arguments);
            var newCloseParen = (ScriptToken)Visit((ScriptNode)node.CloseParen);
            return new ScriptFunctionCall() { Target = newTarget, OpenParent = newOpenParent, Arguments = newArguments, CloseParen = newCloseParen, ExplicitCall = node.ExplicitCall };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptIdentifier node)
        {
            return new ScriptIdentifier() { Value = node.Value };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptIfStatement node)
        {
            var newElseKeyword = (ScriptKeyword)Visit((ScriptNode)node.ElseKeyword);
            var newIfKeyword = (ScriptKeyword)Visit((ScriptNode)node.IfKeyword);
            var newCondition = (ScriptExpression)Visit((ScriptNode)node.Condition);
            var newThen = (ScriptBlockStatement)Visit((ScriptNode)node.Then);
            var newElse = (ScriptConditionStatement)Visit((ScriptNode)node.Else);
            return new ScriptIfStatement() { ElseKeyword = newElseKeyword, IfKeyword = newIfKeyword, Condition = newCondition, Then = newThen, Else = newElse };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptImportStatement node)
        {
            var newImportKeyword = (ScriptKeyword)Visit((ScriptNode)node.ImportKeyword);
            var newExpression = (ScriptExpression)Visit((ScriptNode)node.Expression);
            return new ScriptImportStatement() { ImportKeyword = newImportKeyword, Expression = newExpression };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptIncrementDecrementExpression node)
        {
            var newOperatorToken = (ScriptToken)Visit((ScriptNode)node.OperatorToken);
            var newRight = (ScriptExpression)Visit((ScriptNode)node.Right);
            return new ScriptIncrementDecrementExpression() { OperatorToken = newOperatorToken, Right = newRight, Operator = node.Operator, Post = node.Post };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptIndexerExpression node)
        {
            var newTarget = (ScriptExpression)Visit((ScriptNode)node.Target);
            var newOpenBracket = (ScriptToken)Visit((ScriptNode)node.OpenBracket);
            var newIndex = (ScriptExpression)Visit((ScriptNode)node.Index);
            var newCloseBracket = (ScriptToken)Visit((ScriptNode)node.CloseBracket);
            return new ScriptIndexerExpression() { Target = newTarget, OpenBracket = newOpenBracket, Index = newIndex, CloseBracket = newCloseBracket };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptInterpolatedExpression node)
        {
            var newOpenBrace = (ScriptToken)Visit((ScriptNode)node.OpenBrace);
            var newExpression = (ScriptExpression)Visit((ScriptNode)node.Expression);
            var newCloseBrace = (ScriptToken)Visit((ScriptNode)node.CloseBrace);
            return new ScriptInterpolatedExpression() { OpenBrace = newOpenBrace, Expression = newExpression, CloseBrace = newCloseBrace };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptInterpolatedStringExpression node)
        {
            var newParts = VisitAll(node.Parts);
            return new ScriptInterpolatedStringExpression() { Parts = newParts };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptIsEmptyExpression node)
        {
            var newTarget = (ScriptExpression)Visit((ScriptNode)node.Target);
            var newDotToken = (ScriptToken)Visit((ScriptNode)node.DotToken);
            var newMember = (ScriptVariable)Visit((ScriptNode)node.Member);
            var newQuestionToken = (ScriptToken)Visit((ScriptNode)node.QuestionToken);
            return new ScriptIsEmptyExpression() { Target = newTarget, DotToken = newDotToken, Member = newMember, QuestionToken = newQuestionToken };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptKeyword node)
        {
            return new ScriptKeyword() { Value = node.Value };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptLiteral node)
        {
            return new ScriptLiteral() { Value = node.Value, StringQuoteType = node.StringQuoteType, StringTokenType = node.StringTokenType };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptMemberExpression node)
        {
            var newTarget = (ScriptExpression)Visit((ScriptNode)node.Target);
            var newDotToken = (ScriptToken)Visit((ScriptNode)node.DotToken);
            var newMember = (ScriptVariable)Visit((ScriptNode)node.Member);
            return new ScriptMemberExpression() { Target = newTarget, DotToken = newDotToken, Member = newMember };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptNamedArgument node)
        {
            var newName = (ScriptVariable)Visit((ScriptNode)node.Name);
            var newColonToken = (ScriptToken)Visit((ScriptNode)node.ColonToken);
            var newValue = (ScriptExpression)Visit((ScriptNode)node.Value);
            return new ScriptNamedArgument() { Name = newName, ColonToken = newColonToken, Value = newValue };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptNestedExpression node)
        {
            var newOpenParen = (ScriptToken)Visit((ScriptNode)node.OpenParen);
            var newExpression = (ScriptExpression)Visit((ScriptNode)node.Expression);
            var newCloseParen = (ScriptToken)Visit((ScriptNode)node.CloseParen);
            return new ScriptNestedExpression() { OpenParen = newOpenParen, Expression = newExpression, CloseParen = newCloseParen };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptNopStatement node)
        {
            return new ScriptNopStatement() { };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptObjectInitializerExpression node)
        {
            var newOpenBrace = (ScriptToken)Visit((ScriptNode)node.OpenBrace);
            var newMembers = VisitAll(node.Members);
            var newCloseBrace = (ScriptToken)Visit((ScriptNode)node.CloseBrace);
            return new ScriptObjectInitializerExpression() { OpenBrace = newOpenBrace, Members = newMembers, CloseBrace = newCloseBrace };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptObjectMember node)
        {
            var newName = (ScriptExpression)Visit((ScriptNode)node.Name);
            var newColonToken = (ScriptToken)Visit((ScriptNode)node.ColonToken);
            var newValue = (ScriptExpression)Visit((ScriptNode)node.Value);
            return new ScriptObjectMember() { Name = newName, ColonToken = newColonToken, Value = newValue };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptPage node)
        {
            var newFrontMatter = (ScriptFrontMatter)Visit((ScriptNode)node.FrontMatter);
            var newBody = (ScriptBlockStatement)Visit((ScriptNode)node.Body);
            return new ScriptPage() { FrontMatter = newFrontMatter, Body = newBody };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptParameter node)
        {
            var newName = (ScriptVariable)Visit((ScriptNode)node.Name);
            var newEqualOrTripleDotToken = (ScriptToken)Visit((ScriptNode)node.EqualOrTripleDotToken);
            var newDefaultValue = (ScriptLiteral)Visit((ScriptNode)node.DefaultValue);
            return new ScriptParameter() { Name = newName, EqualOrTripleDotToken = newEqualOrTripleDotToken, DefaultValue = newDefaultValue };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptPipeCall node)
        {
            var newFrom = (ScriptExpression)Visit((ScriptNode)node.From);
            var newPipeToken = (ScriptToken)Visit((ScriptNode)node.PipeToken);
            var newTo = (ScriptExpression)Visit((ScriptNode)node.To);
            return new ScriptPipeCall() { From = newFrom, PipeToken = newPipeToken, To = newTo };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptRawStatement node)
        {
            return new ScriptRawStatement() { Text = node.Text, IsEscape = node.IsEscape };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptReadOnlyStatement node)
        {
            var newReadOnlyKeyword = (ScriptKeyword)Visit((ScriptNode)node.ReadOnlyKeyword);
            var newVariable = (ScriptVariable)Visit((ScriptNode)node.Variable);
            return new ScriptReadOnlyStatement() { ReadOnlyKeyword = newReadOnlyKeyword, Variable = newVariable };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptReturnStatement node)
        {
            var newRetKeyword = (ScriptKeyword)Visit((ScriptNode)node.RetKeyword);
            var newExpression = (ScriptExpression)Visit((ScriptNode)node.Expression);
            return new ScriptReturnStatement() { RetKeyword = newRetKeyword, Expression = newExpression };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptTableRowStatement node)
        {
            var newForOrTableRowKeyword = (ScriptKeyword)Visit((ScriptNode)node.ForOrTableRowKeyword);
            var newVariable = (ScriptExpression)Visit((ScriptNode)node.Variable);
            var newInKeyword = (ScriptKeyword)Visit((ScriptNode)node.InKeyword);
            var newIterator = (ScriptExpression)Visit((ScriptNode)node.Iterator);
            var newNamedArguments = VisitAll(node.NamedArguments);
            var newBody = (ScriptBlockStatement)Visit((ScriptNode)node.Body);
            var newElse = (ScriptElseStatement)Visit((ScriptNode)node.Else);
            return new ScriptTableRowStatement() { ForOrTableRowKeyword = newForOrTableRowKeyword, Variable = newVariable, InKeyword = newInKeyword, Iterator = newIterator, NamedArguments = newNamedArguments, Body = newBody, Else = newElse, SetContinue = node.SetContinue };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptThisExpression node)
        {
            var newThisKeyword = (ScriptKeyword)Visit((ScriptNode)node.ThisKeyword);
            return new ScriptThisExpression() { ThisKeyword = newThisKeyword };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptToken node)
        {
            return new ScriptToken() { Value = node.Value, TokenType = node.TokenType };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptUnaryExpression node)
        {
            var newOperatorToken = (ScriptToken)Visit((ScriptNode)node.OperatorToken);
            var newRight = (ScriptExpression)Visit((ScriptNode)node.Right);
            return new ScriptUnaryExpression() { OperatorToken = newOperatorToken, Right = newRight, Operator = node.Operator };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptWhenStatement node)
        {
            var newWhenKeyword = (ScriptKeyword)Visit((ScriptNode)node.WhenKeyword);
            var newValues = VisitAll(node.Values);
            var newBody = (ScriptBlockStatement)Visit((ScriptNode)node.Body);
            var newNext = (ScriptConditionStatement)Visit((ScriptNode)node.Next);
            return new ScriptWhenStatement() { WhenKeyword = newWhenKeyword, Values = newValues, Body = newBody, Next = newNext };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptWhileStatement node)
        {
            var newWhileKeyword = (ScriptKeyword)Visit((ScriptNode)node.WhileKeyword);
            var newCondition = (ScriptExpression)Visit((ScriptNode)node.Condition);
            var newBody = (ScriptBlockStatement)Visit((ScriptNode)node.Body);
            return new ScriptWhileStatement() { WhileKeyword = newWhileKeyword, Condition = newCondition, Body = newBody };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptWithStatement node)
        {
            var newWithKeyword = (ScriptKeyword)Visit((ScriptNode)node.WithKeyword);
            var newName = (ScriptExpression)Visit((ScriptNode)node.Name);
            var newBody = (ScriptBlockStatement)Visit((ScriptNode)node.Body);
            return new ScriptWithStatement() { WithKeyword = newWithKeyword, Name = newName, Body = newBody };
        }

        /// <inheritdoc/>
        public override ScriptNode Visit(ScriptWrapStatement node)
        {
            var newWrapKeyword = (ScriptKeyword)Visit((ScriptNode)node.WrapKeyword);
            var newTarget = (ScriptExpression)Visit((ScriptNode)node.Target);
            var newBody = (ScriptBlockStatement)Visit((ScriptNode)node.Body);
            return new ScriptWrapStatement() { WrapKeyword = newWrapKeyword, Target = newTarget, Body = newBody };
        }

    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    abstract partial class ScriptVisitor
    {
        /// <summary>Visits ScriptAnonymousFunction.</summary>
        public virtual void Visit(ScriptAnonymousFunction node) => DefaultVisit(node);
        /// <summary>Visits ScriptArgumentBinary.</summary>
        public virtual void Visit(ScriptArgumentBinary node) => DefaultVisit(node);
        /// <summary>Visits ScriptArrayInitializerExpression.</summary>
        public virtual void Visit(ScriptArrayInitializerExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptAssignExpression.</summary>
        public virtual void Visit(ScriptAssignExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptBinaryExpression.</summary>
        public virtual void Visit(ScriptBinaryExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptBlockStatement.</summary>
        public virtual void Visit(ScriptBlockStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptBreakStatement.</summary>
        public virtual void Visit(ScriptBreakStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptCaptureStatement.</summary>
        public virtual void Visit(ScriptCaptureStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptCaseStatement.</summary>
        public virtual void Visit(ScriptCaseStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptConditionalExpression.</summary>
        public virtual void Visit(ScriptConditionalExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptContinueStatement.</summary>
        public virtual void Visit(ScriptContinueStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptElseStatement.</summary>
        public virtual void Visit(ScriptElseStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptEndStatement.</summary>
        public virtual void Visit(ScriptEndStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptEscapeStatement.</summary>
        public virtual void Visit(ScriptEscapeStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptExpressionStatement.</summary>
        public virtual void Visit(ScriptExpressionStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptForStatement.</summary>
        public virtual void Visit(ScriptForStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptFrontMatter.</summary>
        public virtual void Visit(ScriptFrontMatter node) => DefaultVisit(node);
        /// <summary>Visits ScriptFunction.</summary>
        public virtual void Visit(ScriptFunction node) => DefaultVisit(node);
        /// <summary>Visits ScriptFunctionCall.</summary>
        public virtual void Visit(ScriptFunctionCall node) => DefaultVisit(node);
        /// <summary>Visits ScriptIdentifier.</summary>
        public virtual void Visit(ScriptIdentifier node) => DefaultVisit(node);
        /// <summary>Visits ScriptIfStatement.</summary>
        public virtual void Visit(ScriptIfStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptImportStatement.</summary>
        public virtual void Visit(ScriptImportStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptIncrementDecrementExpression.</summary>
        public virtual void Visit(ScriptIncrementDecrementExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptIndexerExpression.</summary>
        public virtual void Visit(ScriptIndexerExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptInterpolatedExpression.</summary>
        public virtual void Visit(ScriptInterpolatedExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptInterpolatedStringExpression.</summary>
        public virtual void Visit(ScriptInterpolatedStringExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptIsEmptyExpression.</summary>
        public virtual void Visit(ScriptIsEmptyExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptKeyword.</summary>
        public virtual void Visit(ScriptKeyword node) => DefaultVisit(node);
        /// <summary>Visits ScriptLiteral.</summary>
        public virtual void Visit(ScriptLiteral node) => DefaultVisit(node);
        /// <summary>Visits ScriptMemberExpression.</summary>
        public virtual void Visit(ScriptMemberExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptNamedArgument.</summary>
        public virtual void Visit(ScriptNamedArgument node) => DefaultVisit(node);
        /// <summary>Visits ScriptNestedExpression.</summary>
        public virtual void Visit(ScriptNestedExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptNopStatement.</summary>
        public virtual void Visit(ScriptNopStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptObjectInitializerExpression.</summary>
        public virtual void Visit(ScriptObjectInitializerExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptObjectMember.</summary>
        public virtual void Visit(ScriptObjectMember node) => DefaultVisit(node);
        /// <summary>Visits ScriptPage.</summary>
        public virtual void Visit(ScriptPage node) => DefaultVisit(node);
        /// <summary>Visits ScriptParameter.</summary>
        public virtual void Visit(ScriptParameter node) => DefaultVisit(node);
        /// <summary>Visits ScriptPipeCall.</summary>
        public virtual void Visit(ScriptPipeCall node) => DefaultVisit(node);
        /// <summary>Visits ScriptRawStatement.</summary>
        public virtual void Visit(ScriptRawStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptReadOnlyStatement.</summary>
        public virtual void Visit(ScriptReadOnlyStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptReturnStatement.</summary>
        public virtual void Visit(ScriptReturnStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptTableRowStatement.</summary>
        public virtual void Visit(ScriptTableRowStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptThisExpression.</summary>
        public virtual void Visit(ScriptThisExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptToken.</summary>
        public virtual void Visit(ScriptToken node) => DefaultVisit(node);
        /// <summary>Visits ScriptUnaryExpression.</summary>
        public virtual void Visit(ScriptUnaryExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptVariableGlobal.</summary>
        public virtual void Visit(ScriptVariableGlobal node) => DefaultVisit(node);
        /// <summary>Visits ScriptVariableLocal.</summary>
        public virtual void Visit(ScriptVariableLocal node) => DefaultVisit(node);
        /// <summary>Visits ScriptWhenStatement.</summary>
        public virtual void Visit(ScriptWhenStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptWhileStatement.</summary>
        public virtual void Visit(ScriptWhileStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptWithStatement.</summary>
        public virtual void Visit(ScriptWithStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptWrapStatement.</summary>
        public virtual void Visit(ScriptWrapStatement node) => DefaultVisit(node);
    }

#if SCRIBAN_PUBLIC
    public
#else
    internal
#endif
    abstract partial class ScriptVisitor<TResult>
    {
        /// <summary>Visits ScriptAnonymousFunction.</summary>
        public virtual TResult Visit(ScriptAnonymousFunction node) => DefaultVisit(node);
        /// <summary>Visits ScriptArgumentBinary.</summary>
        public virtual TResult Visit(ScriptArgumentBinary node) => DefaultVisit(node);
        /// <summary>Visits ScriptArrayInitializerExpression.</summary>
        public virtual TResult Visit(ScriptArrayInitializerExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptAssignExpression.</summary>
        public virtual TResult Visit(ScriptAssignExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptBinaryExpression.</summary>
        public virtual TResult Visit(ScriptBinaryExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptBlockStatement.</summary>
        public virtual TResult Visit(ScriptBlockStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptBreakStatement.</summary>
        public virtual TResult Visit(ScriptBreakStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptCaptureStatement.</summary>
        public virtual TResult Visit(ScriptCaptureStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptCaseStatement.</summary>
        public virtual TResult Visit(ScriptCaseStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptConditionalExpression.</summary>
        public virtual TResult Visit(ScriptConditionalExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptContinueStatement.</summary>
        public virtual TResult Visit(ScriptContinueStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptElseStatement.</summary>
        public virtual TResult Visit(ScriptElseStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptEndStatement.</summary>
        public virtual TResult Visit(ScriptEndStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptEscapeStatement.</summary>
        public virtual TResult Visit(ScriptEscapeStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptExpressionStatement.</summary>
        public virtual TResult Visit(ScriptExpressionStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptForStatement.</summary>
        public virtual TResult Visit(ScriptForStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptFrontMatter.</summary>
        public virtual TResult Visit(ScriptFrontMatter node) => DefaultVisit(node);
        /// <summary>Visits ScriptFunction.</summary>
        public virtual TResult Visit(ScriptFunction node) => DefaultVisit(node);
        /// <summary>Visits ScriptFunctionCall.</summary>
        public virtual TResult Visit(ScriptFunctionCall node) => DefaultVisit(node);
        /// <summary>Visits ScriptIdentifier.</summary>
        public virtual TResult Visit(ScriptIdentifier node) => DefaultVisit(node);
        /// <summary>Visits ScriptIfStatement.</summary>
        public virtual TResult Visit(ScriptIfStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptImportStatement.</summary>
        public virtual TResult Visit(ScriptImportStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptIncrementDecrementExpression.</summary>
        public virtual TResult Visit(ScriptIncrementDecrementExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptIndexerExpression.</summary>
        public virtual TResult Visit(ScriptIndexerExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptInterpolatedExpression.</summary>
        public virtual TResult Visit(ScriptInterpolatedExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptInterpolatedStringExpression.</summary>
        public virtual TResult Visit(ScriptInterpolatedStringExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptIsEmptyExpression.</summary>
        public virtual TResult Visit(ScriptIsEmptyExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptKeyword.</summary>
        public virtual TResult Visit(ScriptKeyword node) => DefaultVisit(node);
        /// <summary>Visits ScriptLiteral.</summary>
        public virtual TResult Visit(ScriptLiteral node) => DefaultVisit(node);
        /// <summary>Visits ScriptMemberExpression.</summary>
        public virtual TResult Visit(ScriptMemberExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptNamedArgument.</summary>
        public virtual TResult Visit(ScriptNamedArgument node) => DefaultVisit(node);
        /// <summary>Visits ScriptNestedExpression.</summary>
        public virtual TResult Visit(ScriptNestedExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptNopStatement.</summary>
        public virtual TResult Visit(ScriptNopStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptObjectInitializerExpression.</summary>
        public virtual TResult Visit(ScriptObjectInitializerExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptObjectMember.</summary>
        public virtual TResult Visit(ScriptObjectMember node) => DefaultVisit(node);
        /// <summary>Visits ScriptPage.</summary>
        public virtual TResult Visit(ScriptPage node) => DefaultVisit(node);
        /// <summary>Visits ScriptParameter.</summary>
        public virtual TResult Visit(ScriptParameter node) => DefaultVisit(node);
        /// <summary>Visits ScriptPipeCall.</summary>
        public virtual TResult Visit(ScriptPipeCall node) => DefaultVisit(node);
        /// <summary>Visits ScriptRawStatement.</summary>
        public virtual TResult Visit(ScriptRawStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptReadOnlyStatement.</summary>
        public virtual TResult Visit(ScriptReadOnlyStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptReturnStatement.</summary>
        public virtual TResult Visit(ScriptReturnStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptTableRowStatement.</summary>
        public virtual TResult Visit(ScriptTableRowStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptThisExpression.</summary>
        public virtual TResult Visit(ScriptThisExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptToken.</summary>
        public virtual TResult Visit(ScriptToken node) => DefaultVisit(node);
        /// <summary>Visits ScriptUnaryExpression.</summary>
        public virtual TResult Visit(ScriptUnaryExpression node) => DefaultVisit(node);
        /// <summary>Visits ScriptVariableGlobal.</summary>
        public virtual TResult Visit(ScriptVariableGlobal node) => DefaultVisit(node);
        /// <summary>Visits ScriptVariableLocal.</summary>
        public virtual TResult Visit(ScriptVariableLocal node) => DefaultVisit(node);
        /// <summary>Visits ScriptWhenStatement.</summary>
        public virtual TResult Visit(ScriptWhenStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptWhileStatement.</summary>
        public virtual TResult Visit(ScriptWhileStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptWithStatement.</summary>
        public virtual TResult Visit(ScriptWithStatement node) => DefaultVisit(node);
        /// <summary>Visits ScriptWrapStatement.</summary>
        public virtual TResult Visit(ScriptWrapStatement node) => DefaultVisit(node);
    }
}